### ISSUE TITLE
错误的核心类型判断

### ISSUE THREAD

**Issue by Dreeam-qwq** [ArtisticCraft/quark-public#2]
使用一些purpur fork，或者paper fork如pufferfish，错误的核心判断方法会导致插件识别成Folia核心

**Comment by Grass-block** [comment]
只要存在RegionScheduler的API服务器（有分区tick）即视为FoliaAPI。
最新版本大部分功能实现已经和API判断脱钩。

如有可能，请提供你的服务端核心下载链接。

**Comment by Grass-block** [comment]
仓库已更改，请移步至https://github.com/Grass-block/Quark-Plugin
